# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\github\shadowsocks-pyqt\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 412)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 10, 251, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.editFrame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.editFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editFrame.sizePolicy().hasHeightForWidth())
        self.editFrame.setSizePolicy(sizePolicy)
        self.editFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.editFrame.setObjectName("editFrame")
        self.formLayout = QtWidgets.QFormLayout(self.editFrame)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.editFrame)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(self.editFrame)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.serverAddrLabel = QtWidgets.QLabel(self.editFrame)
        self.serverAddrLabel.setObjectName("serverAddrLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.serverAddrLabel)
        self.serverAddrEdit = QtWidgets.QLineEdit(self.editFrame)
        self.serverAddrEdit.setObjectName("serverAddrEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.serverAddrEdit)
        self.serverPortLabel = QtWidgets.QLabel(self.editFrame)
        self.serverPortLabel.setObjectName("serverPortLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.serverPortLabel)
        self.serverPortEdit = QtWidgets.QLineEdit(self.editFrame)
        self.serverPortEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.serverPortEdit.setObjectName("serverPortEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.serverPortEdit)
        self.pwdLabel = QtWidgets.QLabel(self.editFrame)
        self.pwdLabel.setObjectName("pwdLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pwdLabel)
        self.pwdEdit = QtWidgets.QLineEdit(self.editFrame)
        font = QtGui.QFont()
        font.setFamily("ADMUI3Lg")
        font.setPointSize(9)
        self.pwdEdit.setFont(font)
        self.pwdEdit.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.pwdEdit.setMaxLength(32767)
        self.pwdEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.pwdEdit.setObjectName("pwdEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pwdEdit)
        self.localAddrLabel = QtWidgets.QLabel(self.editFrame)
        self.localAddrLabel.setObjectName("localAddrLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.localAddrLabel)
        self.localAddrEdit = QtWidgets.QLineEdit(self.editFrame)
        self.localAddrEdit.setObjectName("localAddrEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.localAddrEdit)
        self.localPortLabel = QtWidgets.QLabel(self.editFrame)
        self.localPortLabel.setObjectName("localPortLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.localPortLabel)
        self.localPortEdit = QtWidgets.QLineEdit(self.editFrame)
        self.localPortEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.localPortEdit.setObjectName("localPortEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.localPortEdit)
        self.encryptLabel = QtWidgets.QLabel(self.editFrame)
        self.encryptLabel.setObjectName("encryptLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.encryptLabel)
        self.encryptComboBox = QtWidgets.QComboBox(self.editFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encryptComboBox.sizePolicy().hasHeightForWidth())
        self.encryptComboBox.setSizePolicy(sizePolicy)
        self.encryptComboBox.setObjectName("encryptComboBox")
        self.encryptComboBox.addItem("")
        self.encryptComboBox.addItem("")
        self.encryptComboBox.addItem("")
        self.encryptComboBox.addItem("")
        self.encryptComboBox.addItem("")
        self.encryptComboBox.addItem("")
        self.encryptComboBox.addItem("")
        self.encryptComboBox.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.encryptComboBox)
        self.otaCheckBox = QtWidgets.QCheckBox(self.editFrame)
        self.otaCheckBox.setObjectName("otaCheckBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.otaCheckBox)
        self.timeoutLabel = QtWidgets.QLabel(self.editFrame)
        self.timeoutLabel.setObjectName("timeoutLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.timeoutLabel)
        self.timeoutSpinBox = QtWidgets.QSpinBox(self.editFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeoutSpinBox.sizePolicy().hasHeightForWidth())
        self.timeoutSpinBox.setSizePolicy(sizePolicy)
        self.timeoutSpinBox.setMinimum(10)
        self.timeoutSpinBox.setMaximum(3600)
        self.timeoutSpinBox.setSingleStep(10)
        self.timeoutSpinBox.setProperty("value", 600)
        self.timeoutSpinBox.setObjectName("timeoutSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.timeoutSpinBox)
        self.gridLayout.addWidget(self.editFrame, 1, 0, 1, 1)
        self.configlist = QtWidgets.QListWidget(self.centralWidget)
        self.configlist.setGeometry(QtCore.QRect(10, 10, 221, 301))
        self.configlist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.configlist.setTabKeyNavigation(False)
        self.configlist.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.configlist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.configlist.setObjectName("configlist")
        self.add_config = QtWidgets.QToolButton(self.centralWidget)
        self.add_config.setGeometry(QtCore.QRect(10, 320, 101, 41))
        self.add_config.setObjectName("add_config")
        self.del_config = QtWidgets.QToolButton(self.centralWidget)
        self.del_config.setGeometry(QtCore.QRect(120, 320, 111, 41))
        self.del_config.setObjectName("del_config")
        self.up = QtWidgets.QToolButton(self.centralWidget)
        self.up.setGeometry(QtCore.QRect(10, 360, 101, 41))
        self.up.setObjectName("up")
        self.down = QtWidgets.QToolButton(self.centralWidget)
        self.down.setGeometry(QtCore.QRect(120, 360, 111, 41))
        self.down.setObjectName("down")
        self.b_yes = QtWidgets.QPushButton(self.centralWidget)
        self.b_yes.setGeometry(QtCore.QRect(270, 330, 91, 61))
        self.b_yes.setObjectName("b_yes")
        self.b_exit = QtWidgets.QPushButton(self.centralWidget)
        self.b_exit.setGeometry(QtCore.QRect(410, 330, 91, 61))
        self.b_exit.setObjectName("b_exit")
        self.gridLayoutWidget.raise_()
        self.add_config.raise_()
        self.del_config.raise_()
        self.up.raise_()
        self.down.raise_()
        self.b_yes.raise_()
        self.b_exit.raise_()
        self.configlist.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.b_exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameLabel.setText(_translate("MainWindow", "配置名称"))
        self.nameEdit.setText(_translate("MainWindow", "default"))
        self.serverAddrLabel.setText(_translate("MainWindow", "服务器地址"))
        self.serverAddrEdit.setText(_translate("MainWindow", "127.0.0.1"))
        self.serverPortLabel.setText(_translate("MainWindow", "服务器端口"))
        self.serverPortEdit.setText(_translate("MainWindow", "8388"))
        self.pwdLabel.setText(_translate("MainWindow", "密码"))
        self.pwdEdit.setText(_translate("MainWindow", "password"))
        self.localAddrLabel.setText(_translate("MainWindow", "本地地址"))
        self.localAddrEdit.setText(_translate("MainWindow", "127.0.0.1"))
        self.localPortLabel.setText(_translate("MainWindow", "本地端口"))
        self.localPortEdit.setText(_translate("MainWindow", "1080"))
        self.encryptLabel.setText(_translate("MainWindow", "加密方式"))
        self.encryptComboBox.setItemText(0, _translate("MainWindow", "aes-256-cfb"))
        self.encryptComboBox.setItemText(1, _translate("MainWindow", "aes-128-cfb"))
        self.encryptComboBox.setItemText(2, _translate("MainWindow", "aes-192-cfb"))
        self.encryptComboBox.setItemText(3, _translate("MainWindow", "salsa20"))
        self.encryptComboBox.setItemText(4, _translate("MainWindow", "chacha20"))
        self.encryptComboBox.setItemText(5, _translate("MainWindow", "rc4"))
        self.encryptComboBox.setItemText(6, _translate("MainWindow", "rc4-md5"))
        self.encryptComboBox.setItemText(7, _translate("MainWindow", "table"))
        self.otaCheckBox.setToolTip(_translate("MainWindow", "Turn on one-time authentication and header verification (need server support)"))
        self.otaCheckBox.setText(_translate("MainWindow", "一次验证"))
        self.timeoutLabel.setText(_translate("MainWindow", "超时时间"))
        self.add_config.setText(_translate("MainWindow", "添加"))
        self.del_config.setText(_translate("MainWindow", "删除"))
        self.up.setText(_translate("MainWindow", "上移"))
        self.down.setText(_translate("MainWindow", "下移"))
        self.b_yes.setText(_translate("MainWindow", "确定"))
        self.b_exit.setText(_translate("MainWindow", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

